### ISSUE TITLE
XBox 360 - not transcoding incompatable content

### ISSUE THREAD

**Issue by DavidH2014** [ronenmiz/TVersity#1]
Hi,
I'm running a vanilla installation of 3.5 pro and am trying to play the following video format from my PC running TVersity to my 360.
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 700 MiB
Duration                                 : 1h 23mn
Overall bit rate                         : 1 173 Kbps

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings, BVOP                    : 2
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 1h 23mn
Bit rate                                 : 1 031 Kbps
Width                                    : 624 pixels
Height                                   : 352 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 29.970 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.157
Stream size                              : 615 MiB (88%)
Writing library                          : XviD 1.2.1 (UTC 2008-12-04)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 1h 23mn
Source duration                          : 1h 23mn
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 76.4 MiB (11%)
Alignment                                : Split accross interleaves
Interleave, duration                     : 24 ms (0.72 video frame)
I can find it on the menu but when I click on it it comes up error, incompatible file.
Does anyone know what is incompatible about the file, or how to get TVersity to trans-code without running trans-code on everything?

Thank you.

**Comment by ronenmiz** [comment]
AVI files with XVID and MP3 are sent to the Xbox as is, i.e. never converted to another format. This is because the Xbox can handle such files quite well. Occasionally one may run into a file that does not play. The solution is to configure it in TVersity such that transcoding of this files is forced.
